# Generated by Django 2.2 on 2019-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('di', models.CharField(max_length=1)),
                ('line', models.CharField(max_length=1)),
                ('departure_date', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_date_real', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_date_real', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=1)),
                ('arrival', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
