# Generated by Django 2.2 on 2019-04-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4, unique=True)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('name', models.TextField()),
                ('alias', models.TextField(null=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
            options={
                'verbose_name': 'Aeropoto',
            },
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airpot', to='core.Airport', verbose_name='Aeroporto de Origem'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Chegada Prevista'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date_real',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Chegada Real'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airpot', to='core.Airport', verbose_name='Aeroporto de Destino'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Partida Prevista'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date_real',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Partida Real'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='di',
            field=models.CharField(choices=[(0, 'Voo regular'), (1, 'Voo extra com HOTRAN'), (2, 'Voo extra sem HOTRAN'), (3, 'Voo de retorno'), (4, 'Inclusão de etapa em um voo previsto em HOTRAN'), (5, 'Voo cargueiro'), (6, 'Voo de serviço'), (7, 'Voo de fretamento'), (9, 'Voo charter'), ('A', 'Voo de instrução'), ('B', 'Voo de experiência')], default=0, max_length=1, verbose_name='Código de Autorização'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='icao',
            field=models.CharField(max_length=3, verbose_name='Empresa Área'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='line',
            field=models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional'), ('R', 'Regional'), ('H', 'Sub-regional'), ('E', 'Especial'), ('C', 'Cargueiro'), ('G', 'Cargueiro internacional'), ('L', 'Rede postal')], default='N', max_length=1, verbose_name='Código da Linha'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.IntegerField(verbose_name='Número do Vôo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelado'), ('R', 'Realizado')], default='R', max_length=1, verbose_name='Situação'),
        ),
    ]
